# Generated by Django 3.0 on 2022-06-29 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('NumCh', models.AutoField(primary_key=True, serialize=False)),
                ('DesChambre', models.CharField(default=' ', max_length=255)),
                ('PrixCh', models.PositiveIntegerField(default=0)),
                ('Superficie', models.PositiveIntegerField(default=0)),
                ('NumEtg', models.PositiveIntegerField(default=0)),
                ('categorie', models.CharField(choices=[('YAC', 'AC'), ('NAC', 'NAC'), ('DEL', 'DELUXE'), ('KIN', 'KING'), ('QUE', 'QUEEN')], max_length=20)),
                ('Etat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientt_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('NumHot', models.AutoField(primary_key=True, serialize=False)),
                ('NomHot', models.CharField(max_length=255)),
                ('NbrEtoile', models.IntegerField()),
                ('Desc', models.CharField(max_length=255)),
                ('Adr', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('IdPai', models.AutoField(primary_key=True, serialize=False)),
                ('Mode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('IdRes', models.AutoField(primary_key=True, serialize=False)),
                ('DateDeb', models.DateTimeField()),
                ('DateFin', models.DateTimeField()),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Chambre')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Client')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('IDFac', models.AutoField(primary_key=True, serialize=False)),
                ('DescFac', models.CharField(max_length=300)),
                ('PUFact', models.FloatField(default=0)),
                ('Total', models.FloatField(default=0)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reservation')),
            ],
        ),
        migrations.AddField(
            model_name='chambre',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hotel'),
        ),
    ]
